= Docker image: Alpine Linux with Apache httpd
:caution-caption: ☡ CAUTION
:image_version: 0.5.0
:important-caption: ❗ IMPORTANT
:note-caption: 🛈 NOTE
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:source-highlighter: pygments
:tip-caption: 💡 TIP
:toc-placement: preamble
:toc:
:warning-caption: ⚠ WARNING

Dependencies not listed in the following are under link:resources/[`resources/`]. Please issue all of the following shell statements from within the root directory of this repository. Sections with titles starting with A, B, ... are alternative.

== Dependencies

[options="header"]
|===

| Conditions | Type | Name (URL) | Version constraint

| by default
| data
| CLARIN TLS store under `/root/certstore2/`
| *

| by default +
for build and deployment
| software
| https://www.docker.com/[Docker]
| 1.11

| by default +
for build
| software
| https://www.gnu.org/software/coreutils/coreutils.html[GNU Core utilities]
| 8.25

| by default +
for build
| software
| https://packer.io[Packer]
| 0.10

| by default +
for build and deployment
| software
| https://www.sudo.ws/[Sudo]
| 1.8

|===

== To build the image

=== Enter a build/deploy environment

IMPORTANT: Mind to choose the appropriate Fully Qualified Domain Name (FQDN) for the website in the following.

[source,sh,subs="attributes"]
----
env \
  CONT_NAME='example_website' \
  FQDN='example.clarin.eu' \
  IMAGE_NAME='alpine-apache' \
  IMAGE_TAG='{image_version}' \
  NET_NAME='example_website-net' \
  REGISTRY='docker.clarin.eu' \
  VOL_NAME='example_website-vol' \
    sh
----

[[sec_build]]
=== Build the image

[source,sh]
----
sudo -E packer build 'packer/docker.json'
----

== To deploy the container

=== Configure

[[sec_container_network]]
==== Create the container network

[source,sh]
----
sudo docker network \
  create \
  --driver='bridge' \
  "$NET_NAME"
----

[[sec_data_volume]]
==== Set up the data volume

===== Create the data volume

[source,sh]
----
sudo docker volume \
  create \
  --name="$VOL_NAME"
----

===== Provision the data volume

[source,sh]
----
sudo docker run \
    --rm \
    --interactive \
    --volume="$VOL_NAME"':/var/www/localhost/htdocs/:rw' \
    alpine \
      find '/var/www/localhost/htdocs/' -mindepth '1' -exec rm -rv '{}' +

tar -cvzf - -C 'resources/htdocs/' . | \
  sudo docker run \
    --rm \
    --interactive \
    --volume="$VOL_NAME"':/var/www/localhost/htdocs/:rw' \
    alpine \
        tar -xvzf - -C '/var/www/localhost/htdocs/'
----

[[sec_configure_container]]
==== Configure the container

[source,sh]
----
sudo docker create \
  --entrypoint='/usr/local/bin/dumb-init' \
  --hostname="$FQDN" \
  --name="$CONT_NAME" \
  --net="$NET_NAME" \
  --publish='443:443' \
  --publish='80:80' \
  --restart='unless-stopped' \
  --volume="$VOL_NAME"':/var/www/localhost/htdocs/:ro' \
  --volume='/root/certstore2/:/root/certstore2/:ro' \
  "$REGISTRY/$IMAGE_NAME:$IMAGE_TAG" \
    --single-child \
    /usr/sbin/httpd -D 'FOREGROUND'
----

NOTE: Publish either port 80 (http) or 443 (https) or both. URLs accessed with the http scheme are permanently redirected to their equivalent with the https scheme.

[[sec_start_container]]
=== Start the container

[source,sh]
----
sudo docker start "$CONT_NAME"
----

=== To follow logging output

[source,sh]
----
sudo docker logs -f "$CONT_NAME"
----
